### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Astra-520** [acrylic-style/BedWars#5]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project BedWars: Compilation failure: Compilation failure: 
[ERROR] /D:/matrixbw/src/main/java/xyz/acrylicstyle/bedwars/BedWars.java:[317,38] 找不到符号
[ERROR]   符号:   变量 uuid
[ERROR]   位置: 类 xyz.acrylicstyle.bedwars.BedWars
[ERROR] /D:/matrixbw/src/main/java/xyz/acrylicstyle/bedwars/BedWars.java:[318,38] 找不到符号
[ERROR]   符号:   变量 uuid
[ERROR]   位置: 类 xyz.acrylicstyle.bedwars.BedWars
[ERROR] -> [Help 1]

BedWars.team.values(team).removeReturnCollection(e.getPlayer().getUniqueId()).forEach((uuid, team1) -> {
                if (Bukkit.getPlayer(uuid).getLocation().distance(resourceSpawn) <= 4) {
                    Bukkit.getPlayer(uuid).getInventory().addItem(new ItemStack(type));
                }
            });

**Comment by acrylic-style** [comment]
https://github.com/acrylic-style/BedWars/blob/2707b63147b4f8f40b9a39e4c8ee8e5a126cbe88/src/main/java/xyz/acrylicstyle/bedwars/BedWars.java#L316-L320
(Assuming you have tomeito_lib v0.1.1 and Util v0.2.3 somehow) I'm not sure why you're getting that error. Maybe you have an older version of java? (requires Java 8 at least)
Also, I think you shouldn't use this plugin because it's been unmaintained since November 2019. (along with a lot of bugs)

Here's a quick solution: Don't use this plugin. You can't even resolve the dependencies without building libraries yourself that was committed/published in 2019.

**Comment by Astra-520** [comment]
plz give me tomeitolib0.1.1 and util0.2.3 ok? I need this plugin urgently

**Comment by Astra-520** [comment]
and i have jdk8

**Comment by Astra-520** [comment]
This plugin is very similar to old hypixel beads. Our Chinese friends miss China hypixel very much. China hypixel is the old hypixel beads plug-in, so we want to use this to reproduce a China hypixel. Can we? Thank you for pushing all the necessary LIBS once or saving them to the Internet and sending them to me, which is very important to me

**Comment by acrylic-style** [comment]
> plz give me tomeitolib0.1.1 and util0.2.3 ok? I need this plugin urgently

Why do you need this plugin urgently, when this plugin is just filled with many bugs?

Anyways, there are some libraries you need to build.
- https://github.com/acrylic-style/java-util/tree/eb92e1f4d2d2b2ff381cd8c064ab21173c1de7db - Clone acrylic-style/java-util and checkout `eb92e1f4d2d2b2ff381cd8c064ab21173c1de7db`
- https://github.com/acrylic-style/TomeitoLibrary/tree/4e1094feea03cd1d6111b3dc94ada0450a4191f6 - Clone acrylic-style/TomeitoLibrary and checkout `4e1094feea03cd1d6111b3dc94ada0450a4191f6`

Again, this plugin is unsupported so I cannot help you even if you run into problems.

**Comment by Astra-520** [comment]
thanks you!
